### ISSUE TITLE
和3dTiles混合使用会报错，能否修复？

### ISSUE THREAD

**Issue by ONEGISER** [SuperMap/iClient3D-for-WebGL#1]
Uncaught TypeError: _0x5b72f8.primitive[_0x104821(...)] is not a function
    at Scene.Cesium.<computed>.<computed>.<computed> [as pick]
![image](https://user-images.githubusercontent.com/20511586/131281379-6495c514-3070-45a6-b356-dbaaafc981bb.png)

const _3DTileset = new Cesium.Cesium3DTileset({
            url: 'http://earthsdk.com/v/last/Apps/assets/dayanta/tileset.json'
        })
        _3DTileset.readyPromise.then(function (argument) {
            viewer.scene.primitives.add(_3DTileset)
            viewer.flyTo(_3DTileset)
        })

**Comment by baichongjin** [comment]
我们尽快修复

**Comment by baichongjin** [comment]
已经修改了该缺陷
