### ISSUE TITLE
scene.addS3MTilesLayerByScp()与scene.open()的加载问题。

### ISSUE THREAD

**Issue by Befend** [SuperMap/iClient3D-for-WebGL#10]
scene.open()（目前系统的使用方式）只能打开第一个场景；用scene.addS3MTilesLayerByScp()加载图层无法出现。
![image](https://user-images.githubusercontent.com/31719088/185564485-4150353d-b6f4-486a-b128-193c8893a20e.png)
![image](https://user-images.githubusercontent.com/31719088/185564674-428aaed4-b267-4ede-8986-22523520c885.png)

**Comment by supermapliukaiyun** [comment]
您好, 最新的Cesium_S3MLayer_Plugins代码已更新，请用最新的代码再次尝试下。
