### ISSUE TITLE
SuperMap3D.js插件支持原来webgl三维平台所有功能吗

### ISSUE THREAD

**Issue by yangdengxian** [SuperMap/iClient3D-for-WebGL#11]
你好，咨询一下，之前在webgl平台中的示例功能，比如各种三维空间分析（可视域分析，剖面分析，地表开挖，卷帘对比，坡度坡向等），会在SuperMap3D.js插件中全部集成吗，能提供一个demo吗。谢谢

**Comment by supermapliukaiyun** [comment]
您好，在SuperMap3D.js中基本覆盖了webgl平台中的示例功能。[下载路径](http://support.supermap.com.cn/DownloadCenter/ProductPlatform.aspx) ，打开下载网页，在网络客户端SuperMap iClient3D 11i(2022) for WebGL中下载SuperMap iClient3D 11i (2022) for WebGL，运行范例进行查看。

**Comment by yangdengxian** [comment]
> 



> 您好，在SuperMap3D.js中基本覆盖了webgl平台中的示例功能。[下载路径](http://support.supermap.com.cn/DownloadCenter/ProductPlatform.aspx) ，打开下载网页，在网络客户端SuperMap iClient3D 11i(2022) for WebGL中下载SuperMap iClient3D 11i (2022) for WebGL，运行范例进行查看。

好的，非常感谢，我下载看看示例

**Comment by yangdengxian** [comment]
再问一下啊，这个能和原生cesiumjs结合使用吗，有没有冲突？可独立解耦吗，互不影响。

**Comment by Hurtlz** [comment]
> 再问一下啊，这个能和原生cesiumjs结合使用吗，有没有冲突？可独立解耦吗，互不影响。

同问

**Comment by supermapliukaiyun** [comment]
您好，Cesium_S3MLayer_Plugins是可以与原生的Cesium进行结合使用，兼容了高低版本的Cesium。

**Comment by Hurtlz** [comment]
请问目前是否有集成 addVectorTilesMap(加载MVT矢量瓦片的方法)?

**Comment by metyoo1** [comment]
建议插件完善支持数据加载功能，先考虑如何 把数据加载出来。比如[Hurtlz]说的加MVT，还有加服务token, 三维点线标签这些。希望插件也有专人去测试与维护。谢谢。

**Comment by yangdengxian** [comment]
已解决

**Comment by metyoo1** [comment]
> 已解决

是cesium插件解决了mvt加载的问题吗？ 我看了下还是没有addVectorTilesMap这个接口着，换了接口？
