### ISSUE TITLE
S3MTilesLayer.refresh 未定义

### ISSUE THREAD

**Issue by hgy9473** [SuperMap/iClient3D-for-WebGL#17]
### 问题描述

我想实现调整倾斜模型底部高程，查阅文档 http://support.supermap.com.cn:8090/webgl/docs/Documentation/S3MTilesLayer.html 之后编写代码如下：

```js
  function loadLayer(url) {
    viewer.scene.open(url).then(layers => {
      for (let index = 0; index < layers.length; index++) {
        const layer = layers[index]
        try {
          layer.style3D.bottomAltitude = 5000
          layer.refresh()
        } catch (ex) {
          console.log("ex", ex)
        }
      }
    })
  }
```

代码在执行 layer.refresh() 时报错，TypeError: layer.refresh is not a function。

感谢！

### 环境说明

Cesium版本：1.67
插件：Cesium_S3MLayer_Plugins

**Comment by supermapliukaiyun** [comment]
您好, 最新的Cesium_S3MLayer_Plugins代码已更新，请用最新的代码再次尝试下。
