### ISSUE TITLE
3D模型加载模糊

### ISSUE THREAD

**Issue by MangMax** [SuperMap/iClient3D-for-WebGL#19]
使用  addS3MTilesLayerByScp 加载服务，加载出来的模型都很模糊，尝试过调参数但都没什么效果，而且远处有时候比近处稍微还清楚一点，整体都是放大之后清晰度基本没有变化
![image](https://github.com/SuperMap/iClient3D-for-WebGL/assets/68525017/8a86952a-5e5b-4af8-8aa8-349bfc633722)

![image](https://github.com/SuperMap/iClient3D-for-WebGL/assets/68525017/57aa844c-be45-410a-965d-22e3bd58e711)

![image](https://github.com/SuperMap/iClient3D-for-WebGL/assets/68525017/e067c2a2-53e2-4325-b385-0ad63b148bfe)

**Comment by MangMax** [comment]
尝试等待一段时间加载，cesium出现报错

![image](https://github.com/SuperMap/iClient3D-for-WebGL/assets/68525017/d6dfa537-ae51-455e-a5a5-d391b8dcf110)

![image](https://github.com/SuperMap/iClient3D-for-WebGL/assets/68525017/5091f61a-f289-40b9-93c9-359456ebd8be)

**Comment by MangMax** [comment]
在反复缩放时可以看到网络里是会请求并且没有报错，但模型没有发生变化

**Comment by supermap123** [comment]
您好, 最新的加载s3m缓存代码已更新，请用最新的代码再次尝试下。

**Comment by MangMax** [comment]
> 您好, 最新的加载s3m缓存代码已更新，请用最新的代码再次尝试下。

你好，替换了新的代码出现了一下报错
![image](https://github.com/SuperMap/iClient3D-for-WebGL/assets/68525017/0688078c-60cd-49f3-b4b2-41406508f9eb)
是使用方法上有变动吗？

**Comment by supermap123** [comment]
您好，提交了使用范例，您可以运行范例查看使用方式。
