### ISSUE TITLE
关于api和卡顿现象

### ISSUE THREAD

**Issue by ONEGISER** [SuperMap/iClient3D-for-WebGL#2]

**Comment by ONEGISER** [comment]
能否提供API？现在只看到有open方法，那怎么移除？还有加载咱们的示例场景特别卡顿，甚至鼠标中键左键不起作用！S3MDataSource这个我们还不能用吧？里面的一些依赖文件好像没有

**Comment by pasu** [comment]
1 API后续规范后会提供，目前刚刚提供，目前参考Cesium API以及SuperMap iClient3D for WebGL对应的API，该插件保持和两者的一致
2 移除可使用Scene.Primitives (class PrimitiveCollection)移除的相关API，比如removeAll()
3 加载卡顿这个暂时未做优化，原因是加载解析数据模块在插件中是在主线程运行，所以数据加载会有卡顿。需要考虑在Cesium框架下支持自定义线程的工作，这个我们当作需求，后续会支持。
4 因为我们提供的是插件，交互式操作这块保持和Cesium的方式不变，不清楚你说鼠标中键左键不起作用的具体意义，是希望和SuperMap的交互式功能一致还是其他问题？如果是前者，我们会当作需求，后续可能会提供扩展相机操作模式的模块，提供Cesium相机操作风格，SuperMap相机操作风格这类的模块支持。
5 S3MDataSource目前需要结合Cesium源码使用，所依赖的文件均在Cesium/Source中，请参考使用说明。

**Comment by ONEGISER** [comment]
> 1 API后续规范后会提供，目前刚刚提供，目前参考Cesium API以及SuperMap iClient3D for WebGL对应的API，该插件保持和两者的一致
> 2 移除可使用Scene.Primitives (class PrimitiveCollection)移除的相关API，比如removeAll()
> 3 加载卡顿这个暂时未做优化，原因是加载解析数据模块在插件中是在主线程运行，所以数据加载会有卡顿。需要考虑在Cesium框架下支持自定义线程的工作，这个我们当作需求，后续会支持。
> 4 因为我们提供的是插件，交互式操作这块保持和Cesium的方式不变，不清楚你说鼠标中键左键不起作用的具体意义，是希望和SuperMap的交互式功能一致还是其他问题？如果是前者，我们会当作需求，后续可能会提供扩展相机操作模式的模块，提供Cesium相机操作风格，SuperMap相机操作风格这类的模块支持。
> 5 S3MDataSource目前需要结合Cesium源码使用，所依赖的文件均在Cesium/Source中，请参考使用说明。

明白了，可能描述有问题，左键和中键就是卡顿导致的，没有不起作用，不是一个issue,旨在表达卡顿!
