### ISSUE TITLE
请问如何在包管理器使用？

### ISSUE THREAD

**Issue by luo-geng** [SuperMap/iClient3D-for-WebGL#29]
里面的写法是es，如果在包管理器使用，需要如何配置SUPERMAP_BASE_URL

**Comment by luo-geng** [comment]
发现各种引用大小写的问题
![wechat_2024-08-14_094341_782](https://github.com/user-attachments/assets/f73c0d69-0c71-46a5-b8c1-8dc18d04d313)
![wechat_2024-08-14_094720_101](https://github.com/user-attachments/assets/cbf46264-56de-48b6-adaf-23ad55bd3f10)
![wechat_2024-08-14_094828_183](https://github.com/user-attachments/assets/84607c9f-e9a4-4c39-916c-354905a95f13)

**Comment by xiuyulin** [comment]
可以在window.SUPERMAP_BASE_URL设置就好，设置的路径到thirdParty就好，目的是为了找到对应的wasm数据
