### ISSUE TITLE
S3MDataSource能加载定位到模型位置，但没有显示，什么问题？

### ISSUE THREAD

**Issue by lishulincug** [SuperMap/iClient3D-for-WebGL#4]
S3MDataSource能加载定位到模型位置，但没有显示，也没有报错，什么问题？
![image](https://user-images.githubusercontent.com/13003282/143544576-8f1cbcf2-7a6c-481f-a6b5-956f81c2329b.png)
![image](https://user-images.githubusercontent.com/13003282/143544749-c7d75a0a-4417-4f7d-a332-c83afedf7671.png)

**Comment by supermapliukaiyun** [comment]
您好, 最新的加载s3m缓存代码已更新，请用最新的代码再次尝试下。
