### ISSUE TITLE
Is this a fake open source project？

### ISSUE THREAD

**Issue by ufolr** [SuperMap/iClient3D-for-WebGL#5]
Is this a fake open source project？

**Comment by pasu** [comment]
Thank you for your suggestion.

First, we never claim that it is an open source project, there is a plan to make it open source gradually. Please read the note.

Second, the [S3MDataSource](https://github.com/SuperMap/iClient3D-for-WebGL/blob/main/Cesium_S3MLayer_Plugins/S3MDataSource/Source/DataSources/S3MDataSource.js) is open source, which provides the base function to apply S3M in the Cesium

Thired, [S3MTilesLayer](https://github.com/SuperMap/iClient3D-for-WebGL/tree/main/Cesium_S3MLayer_Plugins/S3MTilesLayer) is still closed source, which provides the advanced functions about S3M.

Finally, we can have the meaningful discussion only if you provide the specific  issue.

**Comment by ufolr** [comment]
Hi @pasu, THX for your answer, it's clear.

I just wanna know the difference between S3MDataSource and S3MTilesLayer. That's it, very Cool.

So. I wonder if we can put these more detailed information in the README or other document? 

This project is under Apache 2.0 License, it's easy to misunderstand the whole project is open source and business friendly, more detailed info would be very helpful.
