### ISSUE TITLE
S3MTilesLayer使用问题

### ISSUE THREAD

**Issue by wzwxwc** [SuperMap/iClient3D-for-WebGL#6]
我按照下面的步骤来使用，遇到了问题：
1、我先下载了Cesium1.81的源代码
https://codeload.github.com/CesiumGS/cesium/zip/refs/tags/1.81
2、依次运行npm i、npm run release都顺利成功
3、把S3MTilesLayer文件夹下的东西覆盖到cesium根目录下
5、运行从S3MTilesLayer文件夹中拷贝的examples/S3MTilesLayer.html，成功运行，可以显示出模型。
6、现在再执行npm run release，没有报错
7、再运行examples/S3MTilesLayer.html这个示例，报错
报错信息如下：
![image](https://user-images.githubusercontent.com/11436176/163337140-d3523d21-0b3e-44e0-8b0c-04f2513401ea.png)

我想咨询：
1、如何解决这个报错信息？
2、我必须执行npm run release，因为我希望得到一个独立的、包含咱们超图Cesium功能的Cesium.js
3、请问咱们的这个cesium插件是基于cesium的哪个版本测试的？
4、我如何自己编译出SuperMap3D.js

万分感谢

**Comment by supermapliukaiyun** [comment]
您好，Cesium插件更新了使用范例，您这边可以参考范例。
