### ISSUE TITLE
cesium1.91删除了原来的cesium.when,使用了promise,会报错

### ISSUE THREAD

**Issue by GGBond-GIS** [SuperMap/iClient3D-for-WebGL#9]
![image](https://user-images.githubusercontent.com/92559206/183790166-e5c47961-c081-4eb3-aea3-ca6a966b2edc.png)

**Comment by Mrzhubingxin** [comment]
![image](https://user-images.githubusercontent.com/92559206/183790267-c9ec9137-8f34-48c6-b45a-e08d6985486f.png)
改完所有的之后cbd可以加载

**Comment by Mrzhubingxin** [comment]
![image](https://user-images.githubusercontent.com/92559206/183790378-d77ee325-ef0c-40ce-bdcd-a6c07817f6f6.png)
instance只加载了一块且报错
![image](https://user-images.githubusercontent.com/92559206/183790461-0fcd8cd0-6b59-4ac8-b46f-4d79307db64a.png)

**Comment by supermapliukaiyun** [comment]
您好, 最新的加载s3m缓存代码已更新，请用最新的代码再次尝试下。
